In [22]:
import torch

# Tensor of shape (r, nstar)

rsigma2 = torch.outer(torch.tensor([1, 2,] ), torch.tensor([10, 20, 30]))
print(rsigma2)


# Vector of shape (nstar,)
sigma2 = torch.tensor([10, 20, 30])   # Shape: (3,)

# Multiply each column by the corresponding element in sigma2
result = rsigma2 * sigma2

print(result)


torch.lgamma(torch.tensor([100]))




tensor([[10, 20, 30],
        [20, 40, 60]])
tensor([[ 100,  400,  900],
        [ 200,  800, 1800]])


tensor([359.1342])

In [8]:
import torch
import numpy as np
import math

beta = torch.tensor(0.5)
torch.log(beta).item()

-0.6931471824645996